---
CONFIG_VERSION: 0.7dev
banned.commands.while.in.game:
- /hub
- /lobby
- /spawn
- /tpa
- /tp
- /tpaccept
- /back
- /home
- /f
- /kill
start.when.full: true
needed.players.to.run.countdown: 1
join.max.health: 20
join.health: 20
damage.cancelled.causes:
- 0
- 3
- 4
- 8
- 12
- 15
drops.on.death: false
player.drop.item: true
chest.refill: true
chest.refill.rate: 240
no.pvp.countdown: 10
death.spectator: true
spectator.quit.item: '355:14'
reward.winning.players: false
reward.value: 100
reward.command: '/'
1st_line: §l§c[§bSW§c]
2nd_line: §l§e{SWNAME}
sign.tick: false
sign.knockBack: true
knockBack.radius.from.sign: 1
knockBack.intensity: 2
knockBack.follow.sign.direction: false
always.spawn.in.defaultLevel: true
clear.inventory.on.respawn&join: false
clear.inventory.on.arena.join: true
clear.effects.on.respawn&join: false
clear.effects.on.arena.join: true
world.generator.air: true
world.compress.tar: false
world.reset.from.tar: true
...
